/*
 * Copyright (C) 2016 Michal Kreuzman
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; version 3.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Authors:
 *      Michal Kreuzman <michal.kreuzman@gmail.com>
 */
#include <gtk/gtk.h>

const gchar *menu_glade =
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
"<!-- Generated with glade 3.16.1 -->"
"<interface>"
"  <requires lib=\"gtk+\" version=\"3.10\"/>"
"  <object class=\"GtkAboutDialog\" id=\"aboutdialog\">"
"    <property name=\"can_focus\">False</property>"
"    <property name=\"halign\">baseline</property>"
"    <property name=\"type\">popup</property>"
"    <property name=\"title\" translatable=\"yes\">About Coundown Indicator</property>"
"    <property name=\"window_position\">center</property>"
"    <property name=\"type_hint\">dialog</property>"
"    <property name=\"gravity\">north-east</property>"
"    <property name=\"program_name\">Coundown Indicator</property>"
"    <property name=\"version\">1.0</property>"
"    <property name=\"copyright\" translatable=\"yes\">@ 2016 Michal Kreuzman</property>"
"    <property name=\"comments\" translatable=\"yes\">A countdown timer capable of notify after given time passed.</property>"
"    <property name=\"license\" translatable=\"yes\">This program is free software; you can redistribute it and/or modify"
"it under the terms of the GNU General Public License as published by"
"the Free Software Foundation; version 3."

"This program is distributed in the hope that it will be useful,"
"but WITHOUT ANY WARRANTY; without even the implied warranty of"
"MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the"
"GNU General Public License for more details."

"You should have received a copy of the GNU General Public License"
"along with this program.  If not, see &lt;http://www.gnu.org/licenses/&gt;.</property>"
"    <property name=\"authors\">Michal Kreuzman</property>"
"    <property name=\"logo\">indicator-countdown.png</property>"
"    <property name=\"logo_icon_name\"/>"
"    <property name=\"wrap_license\">True</property>"
"    <property name=\"license_type\">custom</property>"
"    <child internal-child=\"vbox\">"
"      <object class=\"GtkBox\" id=\"aboutdialog-vbox\">"
"        <property name=\"can_focus\">False</property>"
"        <property name=\"orientation\">vertical</property>"
"        <property name=\"spacing\">2</property>"
"        <property name=\"baseline_position\">top</property>"
"        <child internal-child=\"action_area\">"
"          <object class=\"GtkButtonBox\" id=\"aboutdialog-action_area\">"
"            <property name=\"can_focus\">False</property>"
"            <property name=\"layout_style\">end</property>"
"          </object>"
"          <packing>"
"            <property name=\"expand\">False</property>"
"            <property name=\"fill\">True</property>"
"            <property name=\"pack_type\">end</property>"
"            <property name=\"position\">0</property>"
"          </packing>"
"        </child>"
"        <child>"
"          <placeholder/>"
"        </child>"
"      </object>"
"    </child>"
"  </object>"
"  <object class=\"GtkMenuBar\" id=\"menubar\">"
"    <property name=\"visible\">True</property>"
"    <property name=\"can_focus\">False</property>"
"    <child>"
"      <object class=\"GtkMenuItem\" id=\"menuitem\">"
"        <property name=\"visible\">True</property>"
"        <property name=\"can_focus\">False</property>"
"        <property name=\"label\" translatable=\"yes\">Countdown</property>"
"        <child type=\"submenu\">"
"          <object class=\"GtkMenu\" id=\"indicator_menu\">"
"            <property name=\"visible\">True</property>"
"            <property name=\"can_focus\">False</property>"
"            <child>"
"              <object class=\"GtkMenuItem\" id=\"menuitem_start\">"
"                <property name=\"visible\">True</property>"
"                <property name=\"can_focus\">False</property>"
"                <property name=\"label\" translatable=\"yes\">Start</property>"
"                <signal name=\"activate\" handler=\"on_menuitem_start_activate\" swapped=\"no\"/>"
"              </object>"
"            </child>"
"            <child>"
"              <object class=\"GtkMenuItem\" id=\"menuitem_reset\">"
"                <property name=\"visible\">True</property>"
"                <property name=\"can_focus\">False</property>"
"                <property name=\"label\" translatable=\"yes\">Reset</property>"
"                <signal name=\"activate\" handler=\"on_menuitem_reset_activate\" swapped=\"no\"/>"
"              </object>"
"            </child>"
"            <child>"
"              <object class=\"GtkMenuItem\" id=\"menuitem_about\">"
"                <property name=\"visible\">True</property>"
"                <property name=\"can_focus\">False</property>"
"                <property name=\"label\" translatable=\"yes\">About</property>"
"                <signal name=\"activate\" handler=\"on_menuitem_about_activate\" swapped=\"no\"/>"
"              </object>"
"            </child>"
"            <child>"
"              <object class=\"GtkImageMenuItem\" id=\"menuitem_quit\">"
"                <property name=\"label\">gtk-quit</property>"
"                <property name=\"visible\">True</property>"
"                <property name=\"can_focus\">False</property>"
"                <property name=\"use_underline\">True</property>"
"                <property name=\"use_stock\">True</property>"
"                <signal name=\"activate\" handler=\"gtk_main_quit\" swapped=\"no\"/>"
"              </object>"
"            </child>"
"          </object>"
"        </child>"
"      </object>"
"    </child>"
"  </object>"
"</interface>";
